apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
spec:
  containers:
  - name: mypod
    image: yongbinfeng/tritonserver:rhel8.9_v3
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 16Gi
        cpu: 2
      requests:
        memory: 16Gi
        cpu: 2
    volumeMounts:
    - mountPath: /home/user
      name: user
    - mountPath: /cvmfs
      name: cvmfs
      mountPropagation: HostToContainer
  volumes:
  - name: user
    persistentVolumeClaim:
      claimName: test-vol
  - name: cvmfs
    persistentVolumeClaim:
      claimName: cvmfs
